// Where a hat sits on each pet frame (SPEC §10.5). The art's head is not
// in the same place from one frame to the next — the side view's ear dip is
// fourteen pixels left of where the front view's is — so a hat drawn at one
// fixed spot lands on an ear as often as between them. Each entry is the
// point midway between the pink inner ears at the bottom of the dip between
// them, in the room's head space: `x` from the frame's bottom-centre as the
// atlas snaps it, `y` from the frame's bottom edge. `null` is a frame with no
// ears to wear anything on: the egg, the gravestone, the medicine.
//
// Generated by `npm run head-anchors` and reviewed on its contact sheet;
// the egg, gravestone and medicine frames are hand-set, as is dustbath3,
// whose ears are under the dust in the same pose as dustbath2.

import type { FrameName } from "../atlas.generated";

export type HeadAnchor = { x: number; y: number };

export const HEAD_ANCHORS: Partial<Record<FrameName, HeadAnchor | null>> = {
  blink: { x: -13, y: -126 },
  bored1: { x: -7, y: -104 },
  bored2: { x: -6, y: -104 },
  bored3: { x: -2, y: -104 },
  cheer1: { x: -2, y: -126 },
  cheer2: { x: -2, y: -137 },
  clone1: null,
  clone2: null,
  clone3: null,
  clone4: null,
  clone5: null,
  clone6: null,
  clone7: null,
  clone8: null,
  cry1: { x: 0, y: -126 },
  cry2: { x: 0, y: -126 },
  dead1: null,
  drpepper1: null,
  drpepper2: null,
  dustbath1: { x: -9, y: -126 },
  dustbath2: { x: 2, y: -121 },
  dustbath3: { x: 2, y: -121 }, // dustbath2's pose, ears under the dust
  earTwitch: { x: -13, y: -126 },
  eat1: { x: 0, y: -121 },
  eat2: { x: 0, y: -121 },
  game1: { x: -7, y: -105 },
  game2: { x: -7, y: -105 },
  game3: { x: -7, y: -105 },
  groom1: { x: -13, y: -126 },
  groom2: { x: -13, y: -126 },
  heart1: { x: 0, y: -126 },
  heart2: { x: 0, y: -126 },
  idleFront1: { x: 0, y: -121 },
  idleSide1: { x: -12, y: -121 },
  idleSide2: { x: -11, y: -121 },
  idleSide3: { x: -12, y: -121 },
  lift1: { x: -12, y: -121 },
  lift2: { x: -12, y: -121 },
  lights1: { x: 0, y: -121 },
  lights2: { x: 0, y: -121 },
  pekori: { x: -14, y: -121 },
  shiver1: { x: -11, y: -126 },
  shiver2: { x: -11, y: -126 },
  sick1: { x: -3, y: -110 },
  sick2: { x: -3, y: -110 },
  sleep1: { x: -5, y: -116 },
  sleep2: { x: -5, y: -116 },
  sneeze1: { x: -13, y: -126 },
  sneeze2: { x: -7, y: -126 },
  tea1: { x: -7, y: -105 },
  tea2: { x: -7, y: -105 },
  tired1: { x: -11, y: -116 },
  tired2: { x: -11, y: -116 },
  unhappyEat1: { x: 0, y: -121 },
  unhappyEat2: { x: 0, y: -121 },
  walk1: { x: -13, y: -126 },
  walk2: { x: -13, y: -132 },
  walk3: { x: -13, y: -126 },
  walk4: { x: -13, y: -126 },
  yawn1: { x: -13, y: -126 },
  yawn2: { x: -13, y: -126 },
};
