// The portraits on the family wall (SPEC §22.10).
//
//   npm run art:ancestors
//
// Every generation looks the same in life, so every ancestor's portrait is the
// same picture: the front idle frame's head and shoulders, put through the
// same filter as the framed picture (scripts/art/filter.ts) — on cream paper
// where the sprite is transparent, median-cut to a few colours. The wall hangs
// it at four sizes, and each is filtered from the sprite in its own right:
// shrinking the largest on the canvas would turn pixel art to mush.
//
// One palette serves every size, taken from the largest, so a portrait keeps
// its colours as it shrinks and the room can fade all of them toward sepia
// with one blend per slot.

import { readFileSync, writeFileSync } from "node:fs";
import { PNG } from "pngjs";
import { downscale, letterRows, paletteEntries, quantize, toPalette, type RGB } from "./filter.ts";
import { SPRITE_FRAMES, SPRITE_SHEET_URL } from "../../src/game/atlas.generated.ts";

const SHEET = new URL(`../../public${SPRITE_SHEET_URL}`, import.meta.url);
const GENERATED = new URL("../../src/game/scene/ancestors.generated.ts", import.meta.url);
const CONTACT = new URL("./ancestors-contact.png", import.meta.url);

/** The frame the portrait is taken from, and how much of it: a square from the top — head and shoulders. */
const FRAME = SPRITE_FRAMES.idleFront1;
const CROP = { x: 0, y: 0, w: FRAME.w, h: FRAME.w };
/** The art sizes the wall's slots want, largest first (SPEC §22.10). */
const SIZES = [32, 24, 20, 16] as const;
const COLOURS = 8;
/** Flat pixel art has no thin strokes to protect; a gentle bias keeps the outline from washing out. */
const INK_BIAS = 2;
/** What shows where the sprite is transparent: the photograph's paper. */
const PAPER: RGB = [236, 226, 200];

const sheet = PNG.sync.read(readFileSync(SHEET));
const pixelAt = (x: number, y: number): RGB => {
  const index = ((FRAME.y + y) * sheet.width + (FRAME.x + x)) << 2;
  if (sheet.data[index + 3] === 0) return PAPER;
  return [sheet.data[index]!, sheet.data[index + 1]!, sheet.data[index + 2]!];
};

const grids = SIZES.map((size) => downscale(pixelAt, CROP, size, size, INK_BIAS));
const { palette } = quantize(grids[0]!, COLOURS);
const pictures = SIZES.map((size, index) => ({ size, indices: toPalette(grids[index]!, palette) }));

writeFileSync(
  GENERATED,
  `// GENERATED by scripts/art/ancestors.ts from the sprite sheet's idleFront1 frame.
// Do not edit: re-run \`npm run art:ancestors\` instead (SPEC §22.10).
//
// The same head and shoulders at ${SIZES.join(", ")} pixels, ${palette.length} colours shared
// across the sizes, one letter per pixel, ordered lightest to darkest.

/** Letter to colour, lightest first. */
export const ANCESTOR_PALETTE: Readonly<Record<string, readonly [number, number, number]>> = {
${paletteEntries(palette)}
};

/** The portrait at each size the wall hangs it, largest first. */
export const ANCESTOR_PICTURES: readonly { size: number; rows: readonly string[] }[] = [
${pictures
  .map(
    ({ size, indices }) => `  {
    size: ${size},
    rows: [
${letterRows(indices)
  .map((row) => `      "${row}",`)
  .join("\n")}
    ],
  },`,
  )
  .join("\n")}
];
`,
);

// A contact print at 6x, every size side by side, for looking at.
const SCALE = 6;
const GAP = 4;
const contact = new PNG({
  width: (SIZES.reduce((sum, size) => sum + size, 0) + GAP * (SIZES.length + 1)) * SCALE,
  height: (SIZES[0] + GAP * 2) * SCALE,
});
contact.data.fill(255);
let left = GAP;
for (const { size, indices } of pictures) {
  for (let y = 0; y < size * SCALE; y++) {
    for (let x = 0; x < size * SCALE; x++) {
      const colour = palette[indices[Math.floor(y / SCALE)]![Math.floor(x / SCALE)]!]!;
      const index = ((y + GAP * SCALE) * contact.width + x + left * SCALE) << 2;
      contact.data[index] = colour[0];
      contact.data[index + 1] = colour[1];
      contact.data[index + 2] = colour[2];
      contact.data[index + 3] = 255;
    }
  }
  left += size + GAP;
}
writeFileSync(CONTACT, PNG.sync.write(contact));
console.log(`ancestors: ${SIZES.join("/")}px at ${palette.length} colours → src/game/scene/ancestors.generated.ts + scripts/art/ancestors-contact.png`);
