// Natsumi's frames (SPEC §13.3.2), as editable letter grids. Edit a grid, run
// `npm run art:natsumi`, then `npm run atlas` to repack the sheet.
//
// The style is Jingles' own: a 1px black outline, flat fills, and features
// only a pixel or two across — her eyes are two pixels curving upward. The
// colours come from the reference art: yellow skin, lavender hair that runs
// through pink to blonde at the very tips, and a plain dress with a ribbon at
// the throat and shoes dyed to match it.
//
// Four states, each in two variants — bare-headed and under the witch hat:
//
//   away   turned around, all hair     Makoto may run
//   turn   mid-swing, one eye clear    he may run, briefly
//   watch  facing him                  he must not move
//   grin   she has caught him          he is back at the start
//
// A head grid is 19 rows; the body below the neck is shared, so only her face
// acts. The hat is a cone and a brim stamped over the head's top rows, which
// is what makes the hatted frames taller.

import { createRequire } from "node:module";
import { mkdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const { PNG } = require("pngjs");

const OUT = new URL("../../art/natsumi/", import.meta.url);

const PALETTE = {
  B: [0, 0, 0, 255], // outline, eyes, mouth
  H: [201, 192, 234, 255], // hair
  G: [166, 154, 214, 255], // the part down the back of her head
  K: [226, 158, 196, 255], // the pink her hair passes through
  Y: [240, 226, 174, 255], // and the blonde it ends in
  S: [247, 206, 85, 255], // skin
  D: [124, 112, 190, 255], // her dress
  W: [240, 230, 210, 255], // what shows through the V of her neckline
  P: [176, 126, 168, 255], // ribbon, and the shoes that match it
  A: [96, 104, 168, 255], // the hat
  T: [255, 255, 255, 255], // teeth
};

// Columns, left to right: lock | hair | face (ten wide) | hair | lock.
const HEADS = {
  Away: `
............BBBBBB............
..........BBHHHHHHBB..........
.........BHHHHHHHHHHB.........
........BHHHHHHHHHHHHB........
.......BHHHHHHHHHHHHHHB.......
.......BHHHHHHHHHHHHHHB.......
......BHHHHHHHHHHHHHHHHB......
......BHHHHHHHHHHHHHHHHB......
...BBBHHHHHHHHHHHHHHHHHHBBB...
...BHHBHHBHHHHGGHHHHBHHBHHB...
...BHHBHHBHHHHGGHHHHBHHBHHB...
...BHHBHHBHHHHGGHHHHBHHBHHB...
...BHHBHHBHHHHGGHHHHBHHBHHB...
...BHHBHHBHHHHGGHHHHBHHBHHB...
...BHHBHHBHHHHGGHHHHBHHBHHB...
...BHHBHHBHHHHGGHHHHBHHBHHB...
...BHHBHHBHHHHGGHHHHBHHBHHB...
...BHHBHHBHHHHGGHHHHBHHBHHB...
...BHHBHHBBHHHHHHHHBBHHBHHB...
`,
  // Mid-turn: her near side is still hair, one eye already on him. The turn
  // reads from her face alone — motion ticks beside her head only looked like
  // stray pixels at this size.
  Turn: `
............BBBBBB............
..........BBHHHHHHBB..........
.........BHHHHHHHHHHB.........
........BHHHHHHHHHHHHB........
.......BHHHHHHHHHHHHHHB.......
.......BHHHHHHHHHHHHHHB.......
......BHHHHHHHHHHHHHHHHB......
......BHHHHHHHHHHHHHHHHB......
...BBBHHHHHHHHHHHHHHHHHHBBB...
...BHHBHHBHSSHHHSSHHBHHBHHB...
...BHHBHHBSSSSHHSSSSBHHBHHB...
...BHHBHHBSSSSSSSSSSBHHBHHB...
...BHHBHHBHHHSSSSBBSBHHBHHB...
...BHHBHHBHHHSSSBSSBBHHBHHB...
...BHHBHHBHHHSSSSSSSBHHBHHB...
...BHHBHHBHHHSSSSSSSBHHBHHB...
...BHHBHHBHHHSSSBSSSBHHBHHB...
...BHHBHHBHHHSSSSBBSBHHBHHB...
...BHHBHHBBSSSSSSSSBBHHBHHB...
`,
  Watch: `
............BBBBBB............
..........BBHHHHHHBB..........
.........BHHHHHHHHHHB.........
........BHHHHHHHHHHHHB........
.......BHHHHHHHHHHHHHHB.......
.......BHHHHHHHHHHHHHHB.......
......BHHHHHHHHHHHHHHHHB......
......BHHHHHHHHHHHHHHHHB......
...BBBHHHHHHHHHHHHHHHHHHBBB...
...BHHBHHBHSSHHHSSHHBHHBHHB...
...BHHBHHBSSSSHHSSSSBHHBHHB...
...BHHBHHBSSSSSSSSSSBHHBHHB...
...BHHBHHBSBBSSSSBBSBHHBHHB...
...BHHBHHBBSSBSSBSSBBHHBHHB...
...BHHBHHBSSSSSSSSSSBHHBHHB...
...BHHBHHBSSSSSSSSSSBHHBHHB...
...BHHBHHBSSSBSSBSSSBHHBHHB...
...BHHBHHBSSSSBBSSSSBHHBHHB...
...BHHBHHBBSSSSSSSSBBHHBHHB...
`,
  Grin: `
............BBBBBB............
..........BBHHHHHHBB..........
.........BHHHHHHHHHHB.........
........BHHHHHHHHHHHHB........
.......BHHHHHHHHHHHHHHB.......
.......BHHHHHHHHHHHHHHB.......
......BHHHHHHHHHHHHHHHHB......
......BHHHHHHHHHHHHHHHHB......
...BBBHHHHHHHHHHHHHHHHHHBBB...
...BHHBHHBHSSHHHSSHHBHHBHHB...
...BHHBHHBBBBBSSBBBBBHHBHHB...
...BHHBHHBBTTBSSBTTBBHHBHHB...
...BHHBHHBBBTBSSBBTBBHHBHHB...
...BHHBHHBBBBBSSBBBBBHHBHHB...
...BHHBHHBSSSSSSSSSSBHHBHHB...
...BHHBHHBBBBBBBBBBSBHHBHHB...
...BHHBHHBBTBTBTBTBSBHHBHHB...
...BHHBHHBBBBBBBBBBSBHHBHHB...
...BHHBHHBBSSSSSSSSBBHHBHHB...
`,
};

// One dress. From the front it opens in a V that shows the cream underneath,
// with a ribbon tied at the point of it; from behind there is no V and no
// ribbon, because a bow tied at her throat is not visible from the back.
const dress = (front) => `
...BHHB....BBSSSSBB....BHHB...
...BHHB...BDDDDDDDDB...BHHB...
...BHHBBDDD${front ? "WWWWWWWW" : "DDDDDDDD"}DDDBBHHB...
...BHHBBDDDD${front ? "WWWWWW" : "DDDDDD"}DDDDBBHHB...
...BHHBBDDDDD${front ? "WWWW" : "DDDD"}DDDDDBBHHB...
....BHBBDDDD${front ? "PPWWPP" : "DDDDDD"}DDDDBBHB....
...BDDBBDDDDD${front ? "PPPP" : "DDDD"}DDDDDBBDDB...
...BDDBBDDDD${front ? "PPDDPP" : "DDDDDD"}DDDDBBDDB...
...BDDBBDDDDDDDDDDDDDDBBDDB...
...BSSBBDDDDDDDDDDDDDDBBSSB...
...BSSBBDDDDDDDDDDDDDDBBSSB...
...BBBBBDDDDDDDDDDDDDDBBBBB...
......BDDDDDDDDDDDDDDDDB......
.....BDDDDDDDDDDDDDDDDDDB.....
.....BBBBBBBBBBBBBBBBBBBB.....
...........BSSBBSSB...........
...........BSSBBSSB...........
...........BSSBBSSB...........
...........BSSBBSSB...........
..........PPPP..PPPP..........
.........PPPPP..PPPPP.........
.........BBBBB..BBBBB.........
`;

// The hat sits down on her head, not perched above it: a tall cone rather
// than a squat one, and a brim that covers her whole crown so only her bangs
// show beneath it.
const HAT = `
..............BB..............
.............BAAB.............
.............BAAB.............
............BAAAB.............
............BAAAAB............
...........BAAAAAB............
...........BAAAAAAB...........
..........BAAAAAAAB...........
..........BAAAAAAAAB..........
.........BAAAAAAAAAB..........
..BBBBBBBBAAAAAAAAAABBBBBBBB..
..BAAAAAAAAPPAAAAAAAAAAAAAAB..
..BBBBBBBBBBBBBBBBBBBBBBBBBB..
`;

/** How many rows of crown the brim covers. */
const HAT_COVERS = 8;

const rowsOf = (grid) => grid.trim().split("\n");

// Her hair is lavender for most of each lock, then pink, then blonde at the
// tip. Grading it here rather than in the grids keeps the three bands aligned
// however long the lock ends up.
const LOCK_COLUMNS = [4, 5, 24, 25];
const PINK_ROWS = 2;
const GOLD_ROWS = 2;
const gradeLocks = (rows) => {
  const lockRows = rows.flatMap((row, index) => (LOCK_COLUMNS.some((c) => "HKY".includes(row[c] ?? ".")) ? [index] : []));
  const goldFrom = lockRows.length - GOLD_ROWS;
  const pinkFrom = goldFrom - PINK_ROWS;
  return rows.map((row, index) => {
    const position = lockRows.indexOf(index);
    if (position < 0) return row;
    const letter = position >= goldFrom ? "Y" : position >= pinkFrom ? "K" : "H";
    const chars = [...row];
    for (const c of LOCK_COLUMNS) if ("HKY".includes(chars[c])) chars[c] = letter;
    return chars.join("");
  });
};

const frames = {};
for (const [state, head] of Object.entries(HEADS)) {
  const body = rowsOf(dress(state !== "Away"));
  frames[`natsumi${state}`] = gradeLocks([...rowsOf(head), ...body]);
  frames[`natsumiHat${state}`] = gradeLocks([...rowsOf(HAT), ...rowsOf(head).slice(HAT_COVERS), ...body]);
}

const write = (name, rows) => {
  const width = rows[0].length;
  for (const [index, row] of rows.entries()) {
    if (row.length !== width) throw new Error(`${name}: row ${index} is ${row.length} wide, expected ${width}`);
  }
  const png = new PNG({ width, height: rows.length });
  rows.forEach((row, y) => {
    for (let x = 0; x < width; x += 1) {
      const letter = row[x];
      const rgba = letter === "." ? [0, 0, 0, 0] : PALETTE[letter];
      if (!rgba) throw new Error(`${name}: unknown palette letter "${letter}" at ${x},${y}`);
      const i = (y * width + x) * 4;
      [png.data[i], png.data[i + 1], png.data[i + 2], png.data[i + 3]] = rgba;
    }
  });
  mkdirSync(OUT, { recursive: true });
  writeFileSync(new URL(`${name}@1x.png`, OUT), PNG.sync.write(png));
  return `${name} ${width}x${rows.length}`;
};

console.log(
  Object.entries(frames)
    .map(([name, rows]) => write(name, rows))
    .join("\n"),
);
console.log(`wrote ${Object.keys(frames).length} frames to ${fileURLToPath(OUT)} — re-run \`npm run atlas\` to repack`);
