// Pixel-filters the framed picture from its source drawing (SPEC §22.3).
//
//   npm run art:portrait
//
// The picture on the room's wall is not drawn pixel by pixel — it is a
// photograph of a drawing, put through the same filter every time. Keeping the
// filter in a script rather than the result in a file by hand is what makes it
// reviewable: the grid in src/game/scene/portrait.generated.ts is 48 rows of
// letters, and nobody can tell by eye whether such a thing is right. They can
// tell whether this is.
//
// Three steps, and the middle one is the whole trick:
//
//   crop      to the drawing's own bounding box, so no paper is wasted
//   downscale by area average, weighted toward ink
//   quantize  by median cut
//
// A plain area average bleaches the drawing away. The strokes are one to three
// pixels wide on a 449x420 sheet and the paper around them is white, so at 48
// pixels across, a cell holding one dark line and thirty white neighbours
// averages to very slightly off-white — the whole drawing dissolves. Weighting
// each source pixel by how far it is from white lets the lines carry the cell
// they fall in, which is what the eye does looking at the original.

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { PNG } from "pngjs";
import { downscale, LETTERS, letterRows, paletteEntries, quantize, type Rect, type RGB } from "./filter.ts";

const SOURCE = new URL("./portrait-source.png", import.meta.url);
const GENERATED = new URL("../../src/game/scene/portrait.generated.ts", import.meta.url);
const CONTACT = new URL("./portrait-contact.png", import.meta.url);

/** The framed picture's size in room pixels, and how many colours it keeps. */
const WIDTH = 48;
const HEIGHT = 48;
const COLOURS = 20;

/**
 * How hard ink outweighs paper when a cell is averaged. 0 is a plain mean,
 * which erases the drawing; 3 keeps the strokes without turning the picture
 * into a smudge of outline.
 */
const INK_BIAS = 3;

/** Anything this close to white is paper, for the purpose of finding the art. */
const PAPER = 238;

const source = PNG.sync.read(readFileSync(SOURCE));

const pixelAt = (x: number, y: number): RGB => {
  const index = (y * source.width + x) << 2;
  return [source.data[index]!, source.data[index + 1]!, source.data[index + 2]!];
};

/** The drawing's own extent, so the crop is the art and not the margins. */
const contentBounds = (): Rect => {
  let minX = source.width;
  let minY = source.height;
  let maxX = -1;
  let maxY = -1;
  for (let y = 0; y < source.height; y++) {
    for (let x = 0; x < source.width; x++) {
      const [r, g, b] = pixelAt(x, y);
      if (r > PAPER && g > PAPER && b > PAPER) continue;
      if (x < minX) minX = x;
      if (x > maxX) maxX = x;
      if (y < minY) minY = y;
      if (y > maxY) maxY = y;
    }
  }
  if (maxX < 0) throw new Error("the source drawing is blank");
  return { x: minX, y: minY, w: maxX - minX + 1, h: maxY - minY + 1 };
};

const crop = contentBounds();
const { palette, indices } = quantize(downscale(pixelAt, crop, WIDTH, HEIGHT, INK_BIAS), COLOURS);
if (palette.length > LETTERS.length) throw new Error(`${palette.length} colours needs more letters`);

const rows = letterRows(indices);
const entries = paletteEntries(palette);

writeFileSync(
  GENERATED,
  `// GENERATED by scripts/art/portrait.ts from scripts/art/portrait-source.png.
// Do not edit: re-run \`npm run art:portrait\` instead (SPEC §22.3).
//
// ${WIDTH}x${HEIGHT} at ${palette.length} colours, cropped to the drawing's own
// bounds (${crop.w}x${crop.h} of ${source.width}x${source.height}). One letter per
// pixel, ordered lightest to darkest.

/** Letter to colour, lightest first. */
export const PORTRAIT_PALETTE: Readonly<Record<string, readonly [number, number, number]>> = {
${entries}
};

export const PORTRAIT_PIXELS: readonly string[] = [
${rows.map((row) => `  "${row}",`).join("\n")}
];
`,
);

// A contact print at 6x, for looking at rather than trusting.
const SCALE = 6;
const contact = new PNG({ width: WIDTH * SCALE, height: HEIGHT * SCALE });
for (let y = 0; y < HEIGHT * SCALE; y++) {
  for (let x = 0; x < WIDTH * SCALE; x++) {
    const colour = palette[indices[Math.floor(y / SCALE)]![Math.floor(x / SCALE)]!]!;
    const index = (y * WIDTH * SCALE + x) << 2;
    contact.data[index] = colour[0];
    contact.data[index + 1] = colour[1];
    contact.data[index + 2] = colour[2];
    contact.data[index + 3] = 255;
  }
}
writeFileSync(CONTACT, PNG.sync.write(contact));

const used = new Set(rows.flatMap((row) => [...row]));
console.log(
  `portrait: ${WIDTH}x${HEIGHT}, ${palette.length} colours (${used.size} used), ` +
    `cropped to ${crop.w}x${crop.h} at ${crop.x},${crop.y} → ${readdirSync(new URL(".", GENERATED)).includes("portrait.generated.ts") ? "src/game/scene/portrait.generated.ts" : "generated"} + scripts/art/portrait-contact.png`,
);
